stages:
    - build
    - validate

variables:
    PRECOMMIT_DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"

include:
    - template: "Workflows/Branch-Pipelines.gitlab-ci.yml"
    - template: Jobs/Build.gitlab-ci.yml
    - local: templates/pre-commit.yml
    - project: "DevOps/shared-gitlab-ci-templates"
      file: "security/container-scanning-gitlab-ci.yml"

tenable_container_image_scan:
    extends: .container_image_scan_template
    stage: validate
