stages:
    - build
    - validate

variables:
    PRECOMMIT_DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"

include:
    - template: Jobs/Build.gitlab-ci.yml
    - local: templates/pre-commit.yml
